# Generated by DevOpsGen v2 — Spring Boot (Maven / Java 15)
FROM maven:3.9-eclipse-temurin-15 AS build
WORKDIR /workspace
COPY pom.xml .
COPY src ./src
RUN mvn -B -DskipTests package
RUN test -n "$(ls /workspace/target/*.jar 2>/dev/null)" || (echo "ERROR: no JAR found at /workspace/target/*.jar" && exit 1)

FROM eclipse-temurin:15-jre-alpine
WORKDIR /app
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
COPY --from=build --chown=appuser:appgroup /workspace/target/*.jar /app/app.jar
USER appuser
ENV JAVA_OPTS="-XX:MaxRAMPercentage=75.0 -XX:+UseContainerSupport"
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
